title: Better GitHub status clear
description: >-
  A bookmarklet that lets you pick date and time to clear your GitHub status.

baseurl: "/better_gh_status_clear"
url: "davidstosik.github.io"

markdown: kramdown
theme: minima
